# Generated by Django 4.2.4 on 2023-10-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=15)),
                ('restaurant_on', models.BooleanField(default=False)),
            ],
        ),
    ]
